Added AirCCPropertyListing.cs
CCianfloneDev/cSharpProblems pull request #14
Opened 2022-01-21 18:02 UTC by CCianfloneDev

Requesting DZ-FSDev to review code.

2022-01-21 22:00 UTC, DZ-FSDev requested changes
**Change Requests for AirCCPropertyListing.cs**

2022-01-21 22:00 UTC, DZ-FSDev commented on AirCAndC/AirCCPropertyListing.cs
> +    /// Represents a rental property listing on Air c&c.
- [x] Air C&C

2022-01-21 22:00 UTC, DZ-FSDev commented on AirCAndC/AirCCPropertyListing.cs
> +        private int priceForPackage;
- [ ] Convert value-type fields to props.

2022-01-21 22:00 UTC, DZ-FSDev commented on AirCAndC/AirCCPropertyListing.cs
> +        /// Initializes a listing on Air c&c
- [x] Air C&C

2022-01-21 22:00 UTC, DZ-FSDev commented on AirCAndC/AirCCPropertyListing.cs
> +        public void PrintAmenities()
- [ ] Consider changing to `GetAmenitiesString() : string` after impl.

2022-01-21 22:00 UTC, DZ-FSDev commented on AirCAndC/AirCCPropertyListing.cs
> +        /// Returns a string representation of the listing on Air c&c.
- [x] Air C&C

2022-01-21 22:00 UTC, DZ-FSDev commented on AirCAndC/AirCCPropertyListing.cs
> +            this.amenities = amenities;
- [ ] Consider setting a clone of the list to the field to uphold Encapsulation.

2022-01-21 22:00 UTC, DZ-FSDev commented on AirCAndC/AirCCPropertyListing.cs
> +            if (amenities.Count <= 0)
- [ ] Optimization: This should happen before the loop.

2022-01-21 22:00 UTC, DZ-FSDev commented on AirCAndC/AirCCPropertyListing.cs
> +            return this.amenities;
- [x] Consider returning a clone of the list to uphold Encapsulation.

2022-01-26 14:21 UTC, CCianfloneDev commented on AirCAndC/AirCCPropertyListing.cs
> +            return this.amenities;
Changed method to return clone of list to uphold encapsulation, however this method is not needed at this time, therefor I have commented it out for the time being.

2022-01-27 14:16 UTC, DZ-FSDev requested changes
**CR for #14**
Looks good! I missed this on my initial review:

2022-01-27 14:16 UTC, DZ-FSDev commented on AirCAndC/AirCCPropertyListing.cs
> +        }
- [ ] Currency amount should be changed to use `decimal`

2022-01-27 14:16 UTC, DZ-FSDev commented on AirCAndC/AirCCPropertyListing.cs
> +            string address, RenterPackages rentTypeOffered, int priceForPackage, List<Amenities> amenities)
- [ ] `priceForPackage` should be changed to the `decimal` tyoe

2022-01-28 02:37 UTC, DZ-FSDev approved these changes
Looks good!

2022-01-28 04:38 UTC, merged