Update Zoo.cs
CCianfloneDev/cSharpProblems pull request #20
Opened 2022-01-31 15:44 UTC by CCianfloneDev

Added documentation and Impl. exception handling. For Issue #12

2022-01-31 21:36 UTC, DZ-FSDev requested changes
**CR for #20**

2022-01-31 21:36 UTC, DZ-FSDev commented on ZooKeepingSystem/Zoo.cs
> +        public Zoo(string zooName) : this(zooName, 1, 1, null)
- [ ] Add exception documentation from invoking `this(zooName, 1, 1, null)`

2022-01-31 21:36 UTC, DZ-FSDev commented on ZooKeepingSystem/Zoo.cs
> +            }
- [ ] The logic for state validation should be in the property set accessors.

2022-01-31 21:36 UTC, DZ-FSDev commented on ZooKeepingSystem/Zoo.cs
> +                throw new ArgumentNullException("Name", "Name cannot be null.");
- [ ] Change param name from `Name` to `zooName`
- [ ] zooName also should not be blank i.e. `""`

2022-01-31 21:36 UTC, DZ-FSDev commented on ZooKeepingSystem/Zoo.cs
> +                throw new ArgumentOutOfRangeException("NumberOfCages", "Argument cannot be less than zero.");
- [ ] Change param name to camel case

2022-01-31 21:36 UTC, DZ-FSDev commented on ZooKeepingSystem/Zoo.cs
> +                throw new ArgumentOutOfRangeException("NumberOfZooKeepers", "Argument cannot be less than zero.");
- [ ] Change NumberOfZooKeepers to camel case

2022-01-31 21:36 UTC, DZ-FSDev commented on ZooKeepingSystem/Zoo.cs
> +        /// Gets and sets the name of the zoo.
- [ ] Doesn't have a `public set` so should be documented as a `get` only

2022-02-03 02:03 UTC, DZ-FSDev requested changes
**CR for #20**

2022-02-03 02:03 UTC, DZ-FSDev commented on ZooKeepingSystem/Zoo.cs
> +                    throw new ArgumentOutOfRangeException("numberOfCages", "Argument cannot be less than zero.");
- [x] The argument referenced in property setters is usually `value`

2022-02-03 02:03 UTC, DZ-FSDev commented on ZooKeepingSystem/Zoo.cs
> +                    throw new ArgumentOutOfRangeException("numberOfZooKeepers", "Argument cannot be less than zero.");
- [ ] The argument referenced in property setters is usually `value`

2022-02-03 02:03 UTC, DZ-FSDev commented on ZooKeepingSystem/Zoo.cs
> +                    throw new ArgumentNullException("zooName", "Name cannot be null.");
- [ ] The argument referenced in property setters is usually `value`

2022-02-03 02:03 UTC, DZ-FSDev commented on ZooKeepingSystem/Zoo.cs
> +        /// Initializes a zoo with a name, 1 cages, 1 zoo keeper, and no animals in the care.
- [ ] 1 cage.

2022-02-03 02:03 UTC, DZ-FSDev commented on ZooKeepingSystem/Zoo.cs
> +        /// </exception>
- [ ] This exception shouldn't be thrown by this constructor.

2022-02-03 21:05 UTC, DZ-FSDev approved these changes
Looks good!

2022-02-03 21:28 UTC, CCianfloneDev commented
Exception handl. successfully impl.
All menus are functioning as intended.

2022-02-03 21:28 UTC, merged

2022-02-03 21:29 UTC, CCianfloneDev commented
Accidentally closed PR before merging, I reopened then merged, lol.